version: '3.8'

services:
  mysql-backup:
    image: mysql:8.0
    environment:
      - MYSQL_HOST=mysql-server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - BACKUP_CRON=0 2 * * *
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh
    command: >
      bash -c "
        apt-get update && apt-get install -y cron awscli &&
        chmod +x /backup.sh &&
        echo '$${BACKUP_CRON} /backup.sh' | crontab - &&
        crond -f
      "
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: